apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/infrastructure/nonprod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system