apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busbybox
  name: busbybox
spec:
  containers:
  - image: busybox
    name: busbybox
    command: ["sh","-c","echo Hello Kubernetes! && sleep 3600"]
    resources: {}
